"""remove from email field

Revision ID: 66711b446bc6
Revises: d30f7791b5d1
Create Date: 2024-11-11 10:20:31.434670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66711b446bc6'
down_revision = 'd30f7791b5d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email', schema=None) as batch_op:
        batch_op.drop_column('from_email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email', schema=None) as batch_op:
        batch_op.add_column(sa.Column('from_email', sa.VARCHAR(length=255), nullable=False))

    # ### end Alembic commands ###
